[package]
name = "komiic_cc"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
aidoku = { git = "https://github.com/Aidoku/aidoku-rs.git", version = "0.3.0", features = ["json"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

[profile.release]
panic = "abort"
opt-level = "s"
strip = true
lto = true
